// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yljdgsywqombavyzxhqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsamRnc3l3cW9tYmF2eXp4aHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5OTI3MDgsImV4cCI6MjA3OTU2ODcwOH0.w43aH-aO0CJ7k-niuRNzlx-tV-FhXYaUCMqMLqJLM9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
